# Generated by Django 4.2.7 on 2024-01-04 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_accessrecord_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrecord',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
